name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js (latest LTS)
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      id: run-tests
      run: npm test

    # - name: Run tests and collect coverage
    #   id: run-tests
    #   run: |
    #     # Generate Jest coverage (creates coverage/ and coverage/lcov.info)
    #     # If your npm test script doesn't pass args to Jest, replace with: npx jest --coverage
    #     npm test -- --coverage --coverageReporters=lcov

    # - name: Upload coverage artifact
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: coverage-report
    #     path: coverage/

    # - name: Upload coverage to Codecov
    #   if: always()
    #   uses: codecov/codecov-action@v3
    #   with:
    #     files: coverage/lcov.info
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: false